### ISSUE TITLE
Logitech M720 Triathlon mouse won't connect to Bluetooth

### ISSUE THREAD

**Issue by jdrch** [jdrch/Hardware#50]
Solution:

1. Enter Windows 10's **Bluetooth & other devices** settings
2. Toggle Bluetooth off
3. Toggle Bluetooth on
4. Remove as many *duplicate* devices under **Mouse, keyboard, & pen** heading as you can
5. Long press **1** on mouse until it starts flashing rapidly
6. Click **Add Bluetooth or other device**
7. Click the **M720 Triathlon** entry in the list
8. Click **Connect**

The mouse should now be reconnected.

**Comment by sjakos** [comment]
Thanks for documenting this!

**Comment by logikonabstractions** [comment]
More a hack than a fix, but thanks

**Comment by jdrch** [comment]
> More a hack than a fix, but thanks

I think it's happened only once or twice since I got the mouse in 2018, so 🤷‍♂️

**Comment by rando2** [comment]
For anyone ending up here from Google -- this approach also works for Macs! (Or at least it did for me.)

**Comment by johnphelps** [comment]
Worked for iPhone. Googled for and hour to find this fix. Thanks.

**Comment by projectzenith00** [comment]
Thanks for sharing! Life saver!
